//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articleID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string topic { get; set; }
        public string content { get; set; }
        public int journalist { get; set; }
        public string authorId { get; set; }
    
        public virtual Journalist Journalist1 { get; set; }
    }
}
