//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        public int imageID { get; set; }
        public string userName { get; set; }
        public string name { get; set; }
        public string fileName { get; set; }
        public byte[] image1 { get; set; }
        [Required(ErrorMessage = "Please select the image file")]
        public HttpPostedFileBase File { get; set; }
    }
}
